name: Deploy to Play Store

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Build and Upload to Play Store
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PLAYSTORE_KEY: ${{ secrets.PLAYSTORE_KEY }}
          PLAYSTORE_JSON: ${{ secrets.PLAYSTORE_JSON }}
        run: |
          ./gradlew bundleRelease
          ./gradlew publishBundle --console=plain --no-daemon
